// ROLES SUCCESS

// ROLES FAILURES


// USERS SUCCESS
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const SET_LOGGEDIN_USER = 'SET_LOGGEDIN_USER';
export const SIGNOUT_USER = 'SIGNOUT_USER';

// USERS FAILURES

// DOCUMENTS

// USERS FAILURES
