// SUCCESS MESSAGE
export const SUCCESS_MESSAGE = 'SUCCESS_MESSAGE';

// FAILURE MESSAGE
export const ERROR_MESSAGE = 'ERROR_MESSAGE';

// USERS SUCCESS
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const SET_LOGGEDIN_USER = 'SET_LOGGEDIN_USER';
export const SIGNOUT_USER = 'SIGNOUT_USER';

// USERS FAILURES

// DOCUMENTS
export const GET_ALL_DOCUMENTS_SUCCESS = 'GET_ALL_DOCUMENTS_SUCCESS';
export const CREATE_DOCUMENT_SUCCESS = 'CREATE_DOCUMENT_SUCCESS';
export const UPDATE_DOCUMENT_SUCCESS = 'UPDATE_DOCUMENT_SUCCESS';
// export const GET_MY_DOCUMENTS_SUCCESS = 'GET_MY_DOCUMENTS_SUCCESS';

// SEARCH
export const SEARCH_DOCUMENTS_SUCCESS = 'SEARCH_DOCUMENTS_SUCCESS';
