const faker = require('faker');
const config = require('./config');

const loginId = 'mai';
const password = 'password';

module.exports = {
  'Should not ': browser => {
    browser
      .url('http://localhost:8080/login')
      .waitForElementVisible('body', 20000)
      .waitForElementVisible('input[name=loginId]', 1000)
      .setValue('input[name=loginId]', loginId)
      .waitForElementVisible('input[name=password]', 1000)
      .setValue('input[name=password]', 'password')
      .waitForElementVisible('button[name=login]', 1000)
      .click('button[name=login]')
      .pause(2000)
      .waitForElementVisible('.dashboard', 10000)
      .assert.urlEquals('http://localhost:8080/dashboard')
      .waitForElementVisible('.addDocument', 5000)
      .click('.addDocument')
      .assert.urlEquals('http://localhost:8080/document')

      .waitForElementVisible('input[name=title]', 1000)
      .setValue('input[name=title]', '')
      .waitForElementVisible('select[name=access]', 1000)
      .setValue('select[name=access]', '')
      .waitForElementVisible('.fr-element', 3000)
      .waitForElementVisible('.fr-view', 3000)
      .setValue('div.fr-element', '')
      .waitForElementVisible('#saveDocument', 1000)
      .click('#saveDocument')
      .waitForElementVisible('.toast', 3000)
      .pause(2000)

      .waitForElementVisible('input[name=title]', 1000)
      .setValue('input[name=title]', 'E2E Test')
      .waitForElementVisible('select[name=access]', 1000)
      .setValue('select[name=access]', 'Public')
      .waitForElementVisible('.fr-element', 3000)
      .waitForElementVisible('.fr-view', 3000)
      .setValue('div.fr-element', faker.lorem.paragraph())
      .waitForElementVisible('#saveDocument', 1000)
      .pause(2000)
      .click('#saveDocument')
      .waitForElementVisible('.toast-success', 3000)
      .assert.containsText('.toast-message', 'Document saved successfully')
      .pause(2000)

      .waitForElementVisible('.dashboard', 5000)
      .assert.urlEquals('http://localhost:8080/dashboard')
      .waitForElementVisible('.docTitle', 5000)
      .click('.docTitle')
      .waitForElementVisible('h3', 5000)
      .assert.containsText('h3', 'E2E Test')
      .pause(2000)

      .url('http://localhost:8080/dashboard')
      .waitForElementVisible('.dashboard', 5000)
      .assert.urlEquals('http://localhost:8080/dashboard')
      .waitForElementVisible('.editDoc', 5000)
      .click('.editDoc')
      .pause(2000)
      .waitForElementVisible('input[name=title]', 1000)
      .waitForElementVisible('select[name=access]', 1000)
      .setValue('select[name=access]', 'Public')
      .waitForElementVisible('.fr-element', 3000)
      .waitForElementVisible('.fr-view', 3000)
      .setValue('div.fr-element', faker.lorem.paragraph())
      .waitForElementVisible('#saveDocument', 1000)
      .click('#saveDocument')
      .pause(2000)
      .waitForElementVisible('.toast-success', 3000)
      .assert.containsText('.toast-message', 'Document successfully updated')
      .pause(2000)

      .waitForElementVisible('.dashboard', 10000)
      .assert.urlEquals('http://localhost:8080/dashboard')
      .waitForElementVisible('.deleteDoc', 5000)
      .pause(2000)
      .click('.deleteDoc')
      .pause(1000)
      .waitForElementVisible('.sweet-alert', 5000)
      .waitForElementVisible('.confirm', 5000)
      .pause(2000)
      .click('.confirm')
      .pause(2000)
      .waitForElementVisible('.sweet-alert', 5000)
      .waitForElementVisible('.confirm', 5000)
      .click('.confirm')
      .pause(2000)
      .assert.urlEquals('http://localhost:8080/dashboard')
      .waitForElementVisible('.next-button', 5000)
      .click('.next-button')
      .pause(3000)
      .end();
  }
};
